[METADATA]
modified = "2026-05-22"
expires = "2027-01-01"

[[VALIDATORS]]
public_key = "n9MHkkuAoxognwW7HceSMogtvXAHVtjR6TyhZ8kZZbLu1kCSvhFm"
network = "main"
owner_country = "AU"
server_country = "AU"
unl = "https://vl.ripple.com"

